language: c

os:
    - linux
    - osx

before_install:
    - git submodule update --init --recursive

install:
    - echo $TRAVIS_OS_NAME
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install glib argp-standalone; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libglib2.0-dev libatlas-base-dev libgsl0-dev; fi

script:
    - make
