language: c

os:
    - linux
    - osx

sudo: required
dist: trusty

before_install:
    - git submodule update --init --recursive

install:
    - echo $TRAVIS_OS_NAME
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install glib gsl argp-standalone; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y libglib2.0-dev libatlas-base-dev libgsl0-dev; fi

script:
    - make
      # run test suite
    - (cd src/tests/; make all; make check)
      # run lib demo
    - (cd demo/; make; make demo_lib)
      # run cli demo
    - (cd demo/; make; make demo_cli)

